PUC.LDSI.MVC/Controllers/TurmaController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PUC.LDSI.Domain.Entities;
using PUC.LDSI.MVC.Models;
using AutoMapper;
using PUC.LDSI.Domain.Interfaces.Repository;
using PUC.LDSI.Application.Interfaces;
using Microsoft.AspNetCore.Identity;
using PUC.LDSI.Identity.Entities;

namespace PUC.LDSI.MVC.Controllers
{
    public class TurmaController : BaseController
    {
        private readonly ITurmaAppService _turmaAppService;
        private readonly ITurmaRepository _turmaRepository;

        public TurmaController(UserManager<Usuario> user,
                        ITurmaAppService turmaAppService,
                        ITurmaRepository turmaRepository) : base(user)
        {
            _turmaAppService = turmaAppService;
            _turmaRepository = turmaRepository;
        }

        // GET: Turma
        public async Task<IActionResult> Index()
        {
            var result = _turmaRepository.ObterTodos();

            var turmas = Mapper.Map<List<TurmaViewModel>>(result.ToList());

            return View(turmas);
        }

        // GET: Turma/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Turma/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nome,Id")] TurmaViewModel turma)
        {
            if (ModelState.IsValid)
            {
                var result = await _turmaAppService.AdicionarTurmaAsync(turma.Nome);

                if (result.Success)
                    return RedirectToAction(nameof(Index));
                else
                    throw result.Exception;
            }
            return View(turma);
        }

        // GET: Turma/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var turma = await _turmaRepository.ObterAsync(id.Value);

            if (turma == null)
            {
                return NotFound();
            }

            var viewModel = Mapper.Map<TurmaViewModel>(turma);

            return View(viewModel);
        }

        // POST: Turma/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Nome,Id")] TurmaViewModel turma)
        {
            if (id != turma.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var result = await _turmaAppService.AlterarTurmaAsync(turma.Id, turma.Nome);

                if (result.Success)
                    return RedirectToAction(nameof(Index));
                else
                    throw result.Exception;
            }
            return View(turma);
        }

        // GET: Turma/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var turma = await _turmaRepository.ObterAsync(id.Value);

            if (turma == null)
            {
                return NotFound();
            }

            var viewModel = Mapper.Map<TurmaViewModel>(turma);

            return View(viewModel);
        }

        // POST: Turma/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await _turmaAppService.ExcluirAsync(id);

            if (result.Success)
                return RedirectToAction(nameof(Index));
            else
                throw result.Exception;
        }
    }
}

PUC.LDSI.MVC/Views/Shared/_Layout.cshtml
@{
    ViewData["Title"] = "PUC LDSI - Avaliações";
}
<!DOCTYPE html>
<html style="height:100%">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css">

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
</head>
<body style="height:100%">
    <nav class="navbar custom-navbar-color navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <table>
                    <tbody>
                        <tr>
                            <td><i class="fas fa-chalkboard-teacher" style="display:block;padding: 15px 15px 15px 15px;color:#337ab7;font-size: 20px;position: inherit;"></i></td>
                            <td><a class="navbar-brand" href="#">@ViewData["Title"]</a></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="navbar-collapse collapse">
                <partial name="_MenuPartial" />
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <div class="container body-content" style="height:80%">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - @ViewData["Title"]</p>
        </footer>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>

PUC.LDSI.MVC/Views/Shared/_MenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using PUC.LDSI.Identity.Entities
@inject SignInManager<Usuario> SignInManager
@inject UserManager<Usuario> UserManager

@if (SignInManager.IsSignedIn(User))
{
    @if (User.HasClaim(c => c.Value == "Professor"))
    {
        <a class="btn btn-link navbar-btn navbar-link" style="padding-left:5px;padding-right: 0px;" asp-controller="Turma" asp-action="Index">Turmas</a>
    }
    else
    {
        <a class="btn btn-link navbar-btn navbar-link" style="padding-left:0px;padding-right: 0px;" asp-controller="Home" asp-action="Index">Minhas Avaliações</a>
    }
}